spring:
  #  페이징 작업
  data:
    web:
      pageable:
        one-indexed-parameters: true
        default-page-size: 5

  jpa:
    properties:
      hibernate:
        show_sql: true
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  thymeleaf:
    cache: false
    suffix: .html
    prefix: classpath:/templates/

#  profiles:
#    include: