spring:
  #  페이징 작업
  data:
    web:
      pageable:
        one-indexed-parameters: true
        default-page-size: 5

  jpa:
#    hibernate:
#      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
    defer-datasource-initialization: true

#  sql:
#    init:
#      mode: always

  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb;NON_KEYWORDS=USER
    username: sa
    password:
    driver-class-name: org.h2.Driver

  thymeleaf:
    cache: false
    suffix: .html
    prefix: classpath:/templates/

#  profiles:
#    include:

keynumber:
  jwtKey: "7DP2HXl9I8jdvKYBAS4ZmrciWkkJmjm60E0QMZqTQic="